Библиотечная функция islower() принимает в качестве аргумента один си…
spectrdort/lafore pull request #1
Opened 2021-07-27 16:45 UTC by spectrdort

…мвол (букву) и возвращает ненулевое целое значение в том случае, если

буква является строчной, и нулевое, если буква является заглавной. Описание функции хранится в файле CTYPE.H. Напишите программу, которая
принимает букву от пользователя, а затем выводит нулевое или ненулевое значение в зависимости от того, является ли буква строчной или нет.

2021-07-27 18:41 UTC, DuwazSandbox requested changes

2021-07-27 18:41 UTC, DuwazSandbox commented on Глава 2/5/main.cpp
> +	std::cout << std::islower(n);
А тут разве не предлагалось написать самому логику функции tolower?

2021-07-27 19:27 UTC, spectrdort commented on Глава 2/5/main.cpp
> +	std::cout << std::islower(n);
На вряд ли, мне кажется просто заголовочный файл указан для подключения

2021-07-29 06:22 UTC, Duwaz commented on Глава 2/5/main.cpp
> +	std::cout << std::islower(n);
Ок

2021-07-29 06:22 UTC, Duwaz approved these changes

2021-07-29 06:22 UTC, merged