Модифицируйте программу, описанную в упражнении 7, так, чтобы вместо …
spectrdort/lafore pull request #13
Opened 2021-07-27 17:11 UTC by spectrdort

…вычисления текущей суммы на вашем счете она вычисляла, сколько

лет потребуется для того, чтобы при заданной процентной ставке и величине начального вклада сумма на вашем счете достигла запрашиваемого
вами значения. Для хранения найденного числа лет используйте переменную целого типа (можно отбросить дробную часть значения, полученного
в результате расчета). Самостоятельно выберите тип цикла, подходящий
для решения задачи.

2021-07-27 19:28 UTC, Duwaz requested changes

2021-07-27 19:28 UTC, Duwaz commented on Глава 3/10/main.cpp
> +	years++;
Очень не логично выглядит. Может лишнее или может ожидалось ```int years = 1;``` ?

2021-07-27 19:48 UTC, spectrdort commented on Глава 3/10/main.cpp
> +	years++;
Как вариант

2021-07-29 06:34 UTC, Duwaz approved these changes

2021-07-29 06:34 UTC, merged