Напишите программу, рассчитывающую сумму денег, которые вы получите п…
spectrdort/lafore pull request #7
Opened 2021-07-27 17:09 UTC by spectrdort

…ри вложении начальной суммы с фиксированной процентной ставкой

дохода через определенное количество лет. Пользователь должен вводить
с клавиатуры начальный вклад, число лет и процентную ставку. Примером результата работы программы может быть следующий:
Введите начальный вклад: 3000
Введите число лет: 10
Введите процентную ставку: 5.5
Через 10 лет вы получите 5124.43 доллара.
В конце первого года вы получите 3 000 + (3 000*0.055) = 3165 долларов.
В конце следующего года вы получите 3 165 + (3 165*0.055) = 3339.08 долларов. Подобные вычисления удобно производить с помощью цикла for.

2021-07-27 19:01 UTC, Duwaz requested changes

2021-07-27 19:01 UTC, Duwaz commented on Глава 3/7/main.cpp
> +	std::cout << "\nYears: "; std::cin >> y;
Лучше всё же использовать не '\n', а std::endl.
Если будешь совершать вывод в файл, то в стандартном блокноте на Винде заметишь, что перенос строки не произошёл

2021-07-27 19:35 UTC, spectrdort commented on Глава 3/7/main.cpp
> +	std::cout << "\nYears: "; std::cin >> y;
ок

2021-07-29 06:27 UTC, Duwaz approved these changes

2021-07-29 06:27 UTC, merged